config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'index#index'
  resources :entries
  resources :sessions

  post '/logout' => 'sessions#destroy'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(title: params[:entries][:title], body: params[:entries][:body], tags: params[:entries][:tags])
    if @entry.save
      redirect_to entries_path
    else
      redirect_to root_path
    end
  end

  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  private

  def entry_params
    params.require(:entry).permit(:id, :title, :body, :tags)
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.find_by(params[:username])
    if @admin.authenticate(params[:sessions][:password])
      session[:current_user_id] = @admin.id
      redirect_to root_path
    else
      @error = "Invalid Credentials. Please try again."
      redirect_to sessions_new_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end

  private

  def strong_params
    params.require(:sessions).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:current_user_id]) if session[:current_user_id]
  end

  def logged_in?
    session[:current_user_id] != nil
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/entries/index.html.erb
<div class="parallax-container2">
<div class="parallax"><%= image_tag "http://www.sofiaquintero.com/wp-content/uploads/2014/08/o-EMPTY-CLASSROOM-facebook.jpg" %></div>


<div class="blog_index">
  <% if logged_in? %>
    <%= link_to "new", new_entry_path %>
  <% end %>
  <h3>blog posts</h3>
  <% @entries.each do |entry| %>
  <ul>
    <li class="blog-title"><%= link_to "#{entry.title}", "/entries/#{entry.id}" %></li>
  </ul>
  <% end %>
</div>
</div>

<div class="home"><%= link_to 'home', root_path %></div>

<% if logged_in? %>
  <div class="logout">
    <%= link_to "logout", '/logout', method: "post" %>
  </div>
<% else %>
  <div class="admin">
    <%= link_to "admin", sessions_new_path %>
  </div>
<% end %>

app/views/entries/new.html.erb
<% if !logged_in? %>
  <%= link_to "log in", sessions_new_path %>
<% else %>
  <div class="new_entry">
    <%= form_for(:entries, url: '/entries') do |f| %>

      <%= f.text_field :title, placeholder: 'title' %>

      <%= f.text_area :body, placeholder: 'body' %>

      <%= f.text_field :tags, placeholder: 'tags' %><br>
      <%= submit_tag "post" %>
    <% end %>
  </div>
<% end %>

app/views/entries/show.html.erb
<div class="home"><%= link_to 'home', root_path %></div>


<div class="parallax-container2">
<div class="parallax"><%= image_tag "https://puserscontentstorage.blob.core.windows.net/userimages/ce7802e3-4190-4ef1-a63f-9327380e17b6/635211708360193050_mood-book-pages-grass-hd-wallpaper.jpg" %></div>


<div class="blog_entry z-depth-5">
  <h2><%= @entry.title %></h2>
  <h5><%= @entry.created_at.strftime("%B %e, %Y") %></h5>
  <p><%= simple_format(@entry.body) %></p>
</div>

<div class="back"><%= link_to 'back', entries_path %></div>
</div>

app/views/index/index.html.erb
  <div class="parallax-container">
    <div class="contact">
      <div class="close"><a href="#">[x]</a></div>
      <div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <div class="row">
                <form class="col s12">
                  <div class="row">
                    <div class="input-field col 6">
                      <input placeholder="name" type="text" class="validate">
                      <label for="first_name">name</label>
                    </div>
                  </div>
                  <div class="row">
                    <div class="input-field col 6">
                      <input placeholder="subject" type="text" class="validate">
                      <label for="first_name">subject</label>
                    </div>
                  </div>
                  <div class="row">
                    <div class="input-field col s12">
                      <textarea placeholder="message" id="textarea1" class="materialize-textarea"></textarea>
                      <label for="textarea1"></label>
                    </div>
                  </div>
                  <div class="sub">
                    <a class="waves-effect waves-teal btn-flat">submit</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="links">
      <ul>
        <li><%= link_to 'blog', entries_path %>  </li>
        <li><%= link_to 'projects', 'https://github.com/mrbeal15', :target => "blank" %>  </li>
        <li><%= link_to 'resume', 'https://resume.creddle.io/resume/dfgoivoqc4q', :target => "blank" %>  </li>
        <li class="contact_link"><%= link_to 'contact', entries_path %></li>
      </ul>
    </div>
    <div class="parallax"><img src="http://1.bp.blogspot.com/-MMYkThgt_WA/Tmoe7Cpi2bI/AAAAAAAAAT0/a6VJl1EmADo/s1600/Black+and+White+Highway+Wp+long+goodbye.png"></div>
  </div>

  <div class="quote z-depth-3">
    "So what world are we referring to that would 'let you be great'? I mean LET you be anything?<br> This life is the grind.. Seek and you shall find."--Damian Lillard
  </div>

  <div class="card z-depth-4">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag "chicago2.jpg", class: "activator" %>
    </div>
    <div class="card-content">
      <span class="card-title activator white-text text-darken-4">matt beal<i class="material-icons right">[+]</i></span>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">about me<i class="material-icons right">[-]</i></span>
      <p>Welcome! <br><br> As you know, my name is Matt Beal and I'm currently living in Oklahoma City. Last November I graduated from Dev Bootcamp in the great city of Chicago, and I recently began my first job as a software developer at a start up here in OKC. I can't put into words the growth that I have experienced over the past year, but the quote above comes really close.

      <p><p>Seek and you shall find.<br><br>-Matt B</p>
       </p>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


    <%= yield %>


</body>
</html>